"""
Drift-proof the human docs. Every headline number in ``Degrants.md`` and
``docs/stacks_methodology.md`` is regenerated here from the committed dataset
(``data/stacks/{summary,study}.json``) and injected between named ``STACKS-FACTS`` markers, so the
prose can never silently disagree with ``make stacks_facts``. This applies the same anti-staleness
discipline ``scripts/gen_stacks_architecture.py`` uses for the diagram to the two hand-written docs.

    make stacks_docs                 # rewrite the marked regions from the committed dataset
    make stacks_docs ARGS="--check"  # exit 1 if any doc drifted from the dataset (prints a diff)

A region looks like::

    <!-- STACKS-FACTS:degrants-headline BEGIN (generated by `make stacks_docs` — do not edit) -->
    ...regenerated table...
    <!-- STACKS-FACTS:degrants-headline END -->

Only the text *between* a BEGIN/END pair is owned by the generator; all surrounding prose is left
untouched. The numbers come from one ``_headline()`` dict, so the three rendered variants (two in
Degrants, one in the methodology) cannot disagree with each other or with the data.
"""

from __future__ import annotations

import re
from pathlib import Path

from ictbot.stacks import store

BASE = Path(__file__).resolve().parents[3]
DEGRANTS = BASE / "Degrants.md"
METHODOLOGY = BASE / "docs" / "stacks_methodology.md"

_BEGIN = "<!-- STACKS-FACTS:{name} BEGIN (generated by `make stacks_docs` — do not edit by hand) -->"
_END = "<!-- STACKS-FACTS:{name} END -->"


# --------------------------------------------------------------------------- formatting
def _money_m(x) -> str:
    return f"${float(x) / 1e6:.2f}M" if x else "$0"


def _money(x) -> str:
    return f"${float(x):,.0f}" if x is not None else "n/a"


def _pct(x, n=1) -> str:
    return f"{float(x):.{n}f}%" if x is not None else "n/a"


def _f(x, default=0.0) -> float:
    try:
        return float(x)
    except (TypeError, ValueError):
        return default


# --------------------------------------------------------------------------- canonical numbers
def _headline(summary: dict | None = None, study: dict | None = None) -> dict:
    """The single source of truth for every rendered number — read from committed artifacts."""
    summary = store.read_summary() if summary is None else summary
    study = store.read_study() if study is None else study
    summary = summary or {}
    study = study or {}
    v = study.get("verdict", {})
    thr = v.get("thresholds", {})

    total = _f(summary.get("pools_total"))
    dead = _f(summary.get("pools_dead"))
    live = _f(summary.get("pools_live"))

    flagged = (summary.get("flagged_pools") or [{}])[0]
    m = re.search(r"turnover\s+(\d+(?:\.\d+)?)x", str(flagged.get("note", "")))
    flagged_ratio = int(float(m.group(1))) if m else None
    flagged_symbol = flagged.get("symbol")

    dis = (summary.get("price_disagreements") or [{}])[0]
    btc_pct = None
    if dis.get("agreement"):
        btc_pct = round(abs(_f(dis["agreement"]) - 1.0) * 100, 1)

    tradeable = list(v.get("tradeable_assets_at_2pct", []))
    return {
        "as_of_date": summary.get("as_of_date"),
        "pools_total": int(total),
        "pools_dead": int(dead),
        "dead_pct": round(100 * dead / total, 0) if total else 0,
        "pools_live": int(live),
        "live_pct": round(100 * live / total, 1) if total else 0,
        "tvl_usd_total": _f(summary.get("tvl_usd_total")),
        "volume_reported": _f(summary.get("volume_24h_usd_total")),
        "volume_flagged": _f(summary.get("volume_24h_usd_flagged")),
        "volume_clean": _f(summary.get("volume_24h_usd_clean")),
        "volume_dex_total": _f(summary.get("volume_24h_usd_dex_total")),
        "flagged_ratio": flagged_ratio,
        "flagged_symbol": flagged_symbol,
        "movable_2pct": _f(v.get("movable_at_2pct_usd")),
        "deepest_pool": _f(v.get("deepest_single_pool_usd")),
        "tradeable": tradeable,
        "n_tradeable": int(v.get("n_tradeable_assets", len(tradeable))),
        "min_assets": int(thr.get("min_independent_assets", 3)),
        "deploy_target": _f(thr.get("deploy_target_usd", 50_000)),
        "can_deploy": bool(v.get("can_deploy_50k_at_2pct")),
        "btc_disagreement_pct": btc_pct,
        "btc_symbol": dis.get("symbol"),
        "btc_alex": _f(dis.get("alex")) or None,
        "btc_velar": _f(dis.get("velar")) or None,
    }


def _assets_str(h) -> str:
    a = h["tradeable"]
    return f"{h['n_tradeable']} ({', '.join(a)})" if a else f"{h['n_tradeable']} (none)"


# --------------------------------------------------------------------------- renderers
def render_degrants_headline(h) -> str:
    return "\n".join(
        [
            "| Fact | Measured | Source |",
            "|---|--:|---|",
            f"| Pools across ALEX + Velar + Bitflow | **{h['pools_total']}** | harvest |",
            f"| Pools trading in 24h (live) | **{h['pools_live']}** ({_pct(h['live_pct'])}) | harvest |",
            f"| Total on-chain TVL | **{_money_m(h['tvl_usd_total'])}** | on-chain reserves × price |",
            f"| Reported 24h volume | **{_money_m(h['volume_reported'])}** | ALEX allswaps |",
            f"| …flagged as one endpoint-inconsistent pool | **{_money_m(h['volume_flagged'])}** | "
            f"{h['flagged_ratio']}× turnover |",
            f"| **Clean 24h volume — the entire tradeable ecosystem** | **{_money(h['volume_clean'])}** "
            "| ALEX allswaps |",
            f"| DexScreener free cross-check (all 3 venues) | **{_money(h['volume_dex_total'])}** | "
            "DexScreener aggregator |",
            f"| Capital movable at ≤2% slippage (whole ecosystem) | **{_money(h['movable_2pct'])}** | "
            "on-chain AMM quotes |",
            f"| Assets clearing a $10k depth bar | **{_assets_str(h)}** | depth index |",
            f"| Cross-feed disagreement on the price of BTC | **{_pct(h['btc_disagreement_pct'])}** | "
            "Velar vs ALEX |",
        ]
    )


def render_degrants_verdict(h) -> str:
    assets = ", ".join(h["tradeable"]) or "none"
    return (
        f"The instrument's verdict, in one line: **~{_money(h['movable_2pct'])} can move at ≤2% "
        f"slippage across all of Stacks DeFi, but only {h['n_tradeable']} assets ({assets}) clear "
        f"the $10k depth bar — below the {h['min_assets']} independent assets a rotation needs — so "
        f"systematic trading is not currently viable, and this is the measured threshold at which "
        f"that would flip.** That is the honest, citable finding (§3)."
    )


def render_methodology_headline(h) -> str:
    btc_note = ""
    if h["btc_alex"] and h["btc_velar"]:
        btc_note = f" (ALEX {_money(h['btc_alex'])} vs Velar {_money(h['btc_velar'])})"
    return "\n".join(
        [
            "| Finding | Value |",
            "|---|---|",
            f"| Pools enumerated across ALEX + Velar + Bitflow | **{h['pools_total']}** |",
            f"| Pools with **zero reserves** (dead) | **{h['pools_dead']}** ({_pct(h['dead_pct'], 0)}) |",
            f"| Pools **actually trading** in 24h (live) | **{h['pools_live']}** ({_pct(h['live_pct'])}) |",
            f"| Total TVL (on-chain reserves × USD) | **{_money_m(h['tvl_usd_total'])}** |",
            f"| Reported 24h DEX volume | **{_money_m(h['volume_reported'])}** |",
            f"| …of which **one flagged pool** (ALEX `bridged-btc/bridged-usdt`) | "
            f"**{_money_m(h['volume_flagged'])}** |",
            f"| **Clean 24h volume — the entire rest of Stacks DeFi** | **{_money(h['volume_clean'])}** |",
            f"| DexScreener free cross-check (3-venue, independent) | **{_money(h['volume_dex_total'])}** |",
            f"| Cross-feed disagreement on the price of BTC (Velar vs ALEX) | "
            f"**{_pct(h['btc_disagreement_pct'])}**{btc_note} |",
        ]
    )


# name -> (file, renderer). Names are unique across files.
TARGETS: list[tuple[str, Path, object]] = [
    ("degrants-headline", DEGRANTS, render_degrants_headline),
    ("degrants-verdict", DEGRANTS, render_degrants_verdict),
    ("methodology-headline", METHODOLOGY, render_methodology_headline),
]


# --------------------------------------------------------------------------- marker plumbing
def _block_re(name: str) -> re.Pattern:
    begin = re.escape(_BEGIN.format(name=name))
    end = re.escape(_END.format(name=name))
    return re.compile(begin + r"\n(.*?)\n" + end, re.DOTALL)


def extract_block(text: str, name: str) -> str | None:
    m = _block_re(name).search(text)
    return m.group(1) if m else None


def replace_block(text: str, name: str, content: str) -> str:
    def _sub(_m):
        return f"{_BEGIN.format(name=name)}\n{content}\n{_END.format(name=name)}"

    new, n = _block_re(name).subn(_sub, text)
    if n == 0:
        raise KeyError(f"marker {name!r} not found (insert the BEGIN/END comment pair first)")
    return new


# --------------------------------------------------------------------------- apply / check
def _rendered(headline: dict | None = None) -> list[tuple[str, Path, str]]:
    h = _headline() if headline is None else headline
    return [(name, path, fn(h)) for name, path, fn in TARGETS]


def apply(headline: dict | None = None) -> list[str]:
    """Rewrite every marked region from the committed dataset. Returns the names that changed."""
    changed: list[str] = []
    by_file: dict[Path, list[tuple[str, str]]] = {}
    for name, path, content in _rendered(headline):
        by_file.setdefault(path, []).append((name, content))
    for path, blocks in by_file.items():
        text = path.read_text()
        for name, content in blocks:
            if extract_block(text, name) != content:
                changed.append(name)
            text = replace_block(text, name, content)
        path.write_text(text)
    return changed


def check(headline: dict | None = None) -> tuple[bool, list[dict]]:
    """Compare each marked region to what the committed dataset would render. No writes."""
    drifts: list[dict] = []
    for name, path, content in _rendered(headline):
        current = extract_block(path.read_text(), name) if path.exists() else None
        if current != content:
            drifts.append({"name": name, "file": str(path), "expected": content, "actual": current})
    return (not drifts), drifts
